name: Corre el build y los tests

on: push
  workflow_enabled:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
          cache: "maven"

      - name: Test with Maven
        run: mvn -B test --file pom.xml
